"""
Report Service - Handles report generation, conversion, and export.
Supports Markdown to HTML/PDF conversion and caching.
"""

from __future__ import annotations

import logging
import time
from pathlib import Path
from typing import Any, Dict, Optional

import markdown

from config import settings

logger = logging.getLogger(__name__)

# HTML template for report rendering
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        @page {{
            size: A4;
            margin: 2cm;
        }}
        * {{
            box-sizing: border-box;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC",
                         "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue",
                         Helvetica, Arial, sans-serif;
            line-height: 1.8;
            color: #1a1a1a;
            max-width: 900px;
            margin: 0 auto;
            padding: 40px 20px;
            background: #fafafa;
        }}
        .container {{
            background: #fff;
            padding: 50px 60px;
            border-radius: 8px;
            box-shadow: 0 2px 12px rgba(0,0,0,0.06);
        }}
        h1 {{
            font-size: 28px;
            color: #c41e3a;
            border-bottom: 3px solid #c41e3a;
            padding-bottom: 12px;
            margin-top: 0;
        }}
        h2 {{
            font-size: 22px;
            color: #c41e3a;
            border-bottom: 2px solid #e8d5d8;
            padding-bottom: 8px;
            margin-top: 36px;
        }}
        h3 {{
            font-size: 18px;
            color: #c41e3a;
            margin-top: 28px;
        }}
        h4 {{
            font-size: 16px;
            color: #444;
            margin-top: 20px;
        }}
        p {{
            margin: 12px 0;
            text-align: justify;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            font-size: 14px;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 10px 12px;
            text-align: left;
        }}
        th {{
            background: #f8f1f2;
            color: #c41e3a;
            font-weight: 600;
        }}
        tr:nth-child(even) {{
            background: #fdfbfb;
        }}
        tr:hover {{
            background: #f8f1f2;
        }}
        code {{
            background: #f5f5f5;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 13px;
        }}
        pre {{
            background: #f8f8f8;
            padding: 16px;
            border-radius: 6px;
            overflow-x: auto;
            border-left: 4px solid #c41e3a;
        }}
        blockquote {{
            border-left: 4px solid #c41e3a;
            margin: 16px 0;
            padding: 12px 20px;
            background: #fdf5f5;
            color: #555;
        }}
        ul, ol {{
            padding-left: 24px;
        }}
        li {{
            margin: 6px 0;
        }}
        strong {{
            color: #c41e3a;
        }}
        .header {{
            text-align: center;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 1px solid #eee;
        }}
        .header h1 {{
            border-bottom: none;
            margin-bottom: 8px;
        }}
        .meta {{
            color: #888;
            font-size: 13px;
        }}
        .footer {{
            margin-top: 60px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            text-align: center;
            color: #999;
            font-size: 12px;
        }}
        .score {{
            display: inline-block;
            padding: 4px 12px;
            border-radius: 20px;
            font-weight: 600;
            font-size: 14px;
        }}
        .score-high {{
            background: #e8f5e9;
            color: #2e7d32;
        }}
        .score-mid {{
            background: #fff3e0;
            color: #ef6c00;
        }}
        .score-low {{
            background: #fce4ec;
            color: #c62828;
        }}
        @media print {{
            body {{
                background: white;
                padding: 0;
            }}
            .container {{
                box-shadow: none;
                padding: 0;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{title}</h1>
            <div class="meta">{subtitle}</div>
        </div>
        {content}
        <div class="footer">
            <p>Generated by Huawei Marketing Agent &bull; {timestamp}</p>
        </div>
    </div>
</body>
</html>
"""


class ReportService:
    """Service for generating and exporting reports."""

    def __init__(self):
        self.cache_dir = settings.report_cache_dir
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self._md_converter = markdown.Markdown(
            extensions=[
                "tables",
                "fenced_code",
                "toc",
                "nl2br",
            ]
        )
        logger.info("ReportService initialized")

    def md_to_html(self, md_content: str, title: str = "Report", subtitle: str = "") -> str:
        """Convert Markdown to styled HTML."""
        try:
            # Reset the converter state
            self._md_converter.reset()
            html_body = self._md_converter.convert(md_content)

            timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
            result = HTML_TEMPLATE.format(
                title=title,
                subtitle=subtitle or f"Generated at {timestamp}",
                content=html_body,
                timestamp=timestamp,
            )
            return result
        except Exception as e:
            logger.error(f"HTML conversion failed: {e}")
            # Fallback: wrap markdown in basic HTML
            return self._fallback_html(md_content, title)

    def md_to_pdf(self, md_content: str, title: str = "Report", subtitle: str = "") -> bytes:
        """Convert Markdown to PDF bytes."""
        try:
            html_content = self.md_to_html(md_content, title, subtitle)

            # Try to use weasyprint for PDF generation
            try:
                from weasyprint import HTML
                pdf_bytes = HTML(string=html_content).write_pdf()
                logger.info(f"PDF generated: {len(pdf_bytes)} bytes")
                return pdf_bytes
            except ImportError:
                logger.warning("weasyprint not available, returning HTML as fallback")
                return html_content.encode("utf-8")
            except Exception as e:
                logger.error(f"weasyprint failed: {e}, returning HTML")
                return html_content.encode("utf-8")

        except Exception as e:
            logger.error(f"PDF generation failed: {e}")
            return md_content.encode("utf-8")

    def export_report(
        self,
        report_data: Dict[str, Any],
        export_format: str = "markdown",
    ) -> tuple[bytes, str]:
        """
        Export a report in the specified format.

        Args:
            report_data: Report data dict with 'title', 'content', 'markdown'
            export_format: 'markdown', 'html', or 'pdf'

        Returns:
            (file_bytes, content_type)
        """
        title = report_data.get("title", "Report")
        md_content = report_data.get("markdown", report_data.get("content", ""))
        subtitle = report_data.get("subtitle", "")

        if export_format == "html":
            html = self.md_to_html(md_content, title, subtitle)
            return html.encode("utf-8"), "text/html; charset=utf-8"

        elif export_format == "pdf":
            pdf_bytes = self.md_to_pdf(md_content, title, subtitle)
            return pdf_bytes, "application/pdf"

        else:  # markdown
            md_bytes = md_content.encode("utf-8")
            return md_bytes, "text/markdown; charset=utf-8"

    def cache_report(self, session_id: str, report_type: str, report_data: Dict[str, Any]) -> Path:
        """Cache a report to disk for later retrieval."""
        cache_file = self.cache_dir / f"{session_id}_{report_type}.json"
        import json
        with open(cache_file, "w", encoding="utf-8") as f:
            json.dump(report_data, f, ensure_ascii=False, default=str)
        logger.info(f"Report cached: {cache_file}")
        return cache_file

    def get_cached_report(self, session_id: str, report_type: str) -> Optional[Dict[str, Any]]:
        """Retrieve a cached report from disk."""
        cache_file = self.cache_dir / f"{session_id}_{report_type}.json"
        if cache_file.exists():
            import json
            with open(cache_file, "r", encoding="utf-8") as f:
                return json.load(f)
        return None

    def _fallback_html(self, md_content: str, title: str) -> str:
        """Fallback HTML generation when markdown conversion fails."""
        escaped = (
            md_content
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )
        html_body = f"<pre>{escaped}</pre>"
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        return HTML_TEMPLATE.format(
            title=title,
            subtitle=f"Generated at {timestamp}",
            content=html_body,
            timestamp=timestamp,
        )


# Global singleton
report_service = ReportService()
